config paths..

diff --git a/bin/create_alias b/bin/create_alias
--- a/bin/create_alias
+++ b/bin/create_alias
@@ -11,12 +11,12 @@ alias_domain=$(cut -f1 -d@ <<<$alias_email);
 alias_username=$(cut -f2 -d@ <<<$alias_email);
 container_name=$3
 vmail_dir=$(docker exec -ti $container_name postconf | grep ^virtual_mailbox_base | awk '{print $NF}');
-valiases=$(docker exec -ti $container_name postconf | grep ^virtual_alias_maps | awk -F: '{print $NF}');
+valiases=$(docker inspect -f '{{ .HostConfig.Binds }}' $container_name | sed 's/ /\n/g' | grep /config | awk -F: '{print $1}');
 if [ -f $valiases ]; then
-	if ! grep -q "$alias_email" $valiases; then
+	if ! grep -q "$alias_email" $valiases/virtual_aliases; then
 		if [[ -d $vmail_dir/$alias_domain/$alias_username ]]; then
 			echo -n "Adding alias for $email to forward to $alias_email.."
-			echo "$email $alias_email" >> $valiases
+			echo "$email $alias_email" >> $valiases/virtual_aliases
 			echo "done."
 			echo "Restart Docker container to reload configuration changes."
 		else
@@ -27,6 +27,6 @@ if [ -f $valiases ]; then
 		echo "Alias $alias_email already exists in the virtual aliases configuration file. Maybe you need to restart the Docker container?"
 		exit 1
 	fi
-	echo "Alias configuration file ($valiases) could not be found!"
+	echo "Alias configuration file ($valiases/virtual_aliases) could not be found!"
 	exit 1
 fi
diff --git a/bin/create_email b/bin/create_email
--- a/bin/create_email
+++ b/bin/create_email
@@ -8,20 +8,20 @@ username=$(cut -f1 -d@ <<<$email);
 domain=$(cut -f2 -d@ <<<$email);
 container_name=$2
 vmail_dir=$(docker exec -ti $container_name postconf | grep ^virtual_mailbox_base | awk '{print $NF}');
-vmailboxes=$(docker exec -ti $container_name postconf | grep ^virtual_mailbox_domains | awk '{print $NF}');
+vmailboxes=$(docker inspect -f '{{ .HostConfig.Binds }}' $container_name | sed 's/ /\n/g' | grep /config | awk -F: '{print $1}');
 if [ -f $vmailboxes ]; then
-	if ! grep -q "$email" $vmailboxes; then
+	if ! grep -q "$email" $vmailboxes/virtual_mailboxes; then
 		echo -n "Creating virtual mailbox directory $vmail_dir/$domain/$username.."
 		mkdir -p $vmail_dir/$domain/$username
 		echo "done."
 		echo -n "Adding mailbox $email to virtual mailbox configuration file.."
-		echo "$email $domain/$username/" >> $vmailboxes
+		echo "$email $domain/$username/" >> $vmailboxes/virtual_mailboxes
 		echo "done."
 		echo "Restart Docker container to reload configuration changes."
 	else
 		echo "E-mail $email already exists in the virtual mailbox configuration file. Maybe you need to restart the Docker container?"
 	fi
 else
-	echo "Virtual mailbox configuration file ($vmailboxes) could not be found!"
+	echo "Virtual mailbox configuration file ($vmailboxes/virtual_mailboxes) could not be found!"
 	exit 1
 fi
